### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [iext/qgisPluginGrid2Tif#5]
# Problem

Please explain plugin usefulness 
![plugin](https://user-images.githubusercontent.com/2510900/59745672-98915100-9275-11e9-98af-3b83b65ad92e.png)

**Comment by iext** [comment]
The utility information is displayed in the GIF on the [readme.md](https://github.com/iext/qgisPluginGrid2Tif) page. Я внёс изменения в файл metadata.txt

**Comment by iext** [comment]
The utility information is displayed in the GIF on the readme.md page. I made changes to the metadata.txt file

**Comment by iext** [comment]
This plugin allows you to save the contents of the map for selected grid objects in the tif + mapinfo file. You can use it to create attached images in raster format.

**Comment by NyakudyaA** [comment]
Thanks,  will look at approval later during the day. Can you add that in the README
